HackView/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('user/', include('users.urls')),
                  path('', include('challenges.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

challenges/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.index, name='home'),
    path('challenges/', views.challengeList, name='challenge-list'),
    path('myChallenges/', views.hosterMyChallenges, name='my-challenges'),
    path('myProposals/', views.innovatorMyProposals, name='my-proposals'),
    path('challenge-detail/<int:id>/', views.challengeDetail, name='challenge-detail'),
    path('challenge-submissions/<int:id>/', views.viewChallengeSubmission, name='view-submissions'),
    path('review-submissions/<int:id>/', views.reviewSubmission, name='review-submissions'),
    path('challenge-update/<int:id>/', views.challengeUpdate, name='challenge-update'),
    path('challenge-delete/<int:id>/', views.challengeDetail, name='challenge-delete'),
    path('create-challenge/', views.CreateChallenge, name='create-challenge'),
    path('submitchallenge/<int:id>', views.challengeSubmission, name='challenge-submission'),

]

users/urls.py
from urllib import request

from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin-register/', views.AdminUserRegisteration, name='admin-user-registration'),
    path('innovator-register/', views.InnovatorUserRegisteration, name='innovator-user-registration'),
    path('login/', views.loginPage, name='user-login'),
    path('logout/', views.logoutuser, name='user-logout'),
    path('profile/', views.myprofile, name='user-profile'),

]

challenges/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Challenges(models.Model):
    challenge_title = models.CharField(max_length=100)
    challenge_image = models.ImageField(null=True, upload_to='challenge-images')
    challenge_description = models.TextField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.challenge_title


class Submission(models.Model):
    challenge = models.ForeignKey(Challenges, on_delete=models.SET_NULL, null=True)
    applyer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    qa1 = models.TextField()
    qa2 = models.TextField()
    qa3 = models.TextField()
    qa4 = models.TextField()
    qa5 = models.TextField()
    qa6 = models.TextField()
    submitted_at = models.DateTimeField(auto_now_add=True)
    review_status = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.challenge.challenge_title} by {self.applyer}'


class ReviewSubmissionScore(models.Model):
    MARK_CHOICES = (
        ('0', '0'), ('2', '2'), ('4', '4'),
        ('6', '6'), ('10', '10'), ('20', '20')
    )
    submission = models.OneToOneField(Submission, on_delete=models.CASCADE)
    criteria1 = models.CharField(max_length=10, choices=MARK_CHOICES, default=0)
    criteria2 = models.CharField(max_length=10, choices=MARK_CHOICES, default=0)
    criteria3 = models.CharField(max_length=10, choices=MARK_CHOICES, default=0)
    criteria4 = models.CharField(max_length=10, choices=MARK_CHOICES, default=0)
    criteria5 = models.CharField(max_length=10, choices=MARK_CHOICES, default=0)
    tip = models.TextField(null=True, blank=True)
    TotalScore = models.CharField(max_length=10, null=False)

    reviewed_by = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return f' Submission for {self.submission.challenge}'

challenges/forms.py
from django import forms
from .models import Submission, Challenges, ReviewSubmissionScore
from django.utils.translation import ugettext_lazy as _


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Submission
        exclude = ('challenge', 'applyer', 'review_status', 'submitted_at')

        labels = {
            'qa1': _('1.Can you describe the problem in your own words exactly how you experience it ?'),
            'qa2': _('2.How have you tried to solve this problem before? Can you explain the solution?'),
            'qa3': _('3.Why did you not make tht solution permanent?What were the gaps in the solution?'),
            'qa4': _('4.What are the other constraints?challenges that have to be overcome or accommodated while '
                     'solving the problem?'),
            'qa5': _('5.How will you benefit from solving the problem?How much is solving this problem worth to you ?'),
            'qa6': _('6.How important to you is solving this problem among other priorities?'),
        }


class ChallengeCreationForm(forms.ModelForm):
    class Meta:
        model = Challenges
        exclude = ('created_by',)


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewSubmissionScore
        fields = ['criteria1', 'criteria2', 'criteria3', 'criteria4', 'criteria5', 'tip']
        labels = {
            'criteria1': _('Is the Problem Statement Defined Clearly ?'),
            'criteria2': _('Is the Problem Worth Solving ?'),
            'criteria3': _('Is the Chosen Target Customer(Type/Profile) Strongly Motivated to solve the Problem ?'),
            'criteria4': _('Is the Core Value Proportion Defined,Quantified And Validated ?'),
            'criteria5': _('Is the Problem Statement Defined Clearly ?'),
            'tip': _('Any tip for submitters ? (Optional)'),
        }

    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            if isinstance(field.widget, forms.Select):
                field.widget = forms.RadioSelect()

challenges/views.py
from django.db import IntegrityError
from django.shortcuts import render, get_object_or_404, redirect
from .forms import QuestionForm, ChallengeCreationForm, ReviewForm
from .models import Submission, Challenges
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages


# Create your views here.


def index(request):
    context = {
    }
    return render(request, template_name='challenges/Home.html', context=context)


def challengeList(request):
    queryset = Challenges.objects.all()
    context = {
        'challenges': queryset,
    }
    return render(request, template_name='challenges/challengeList.html', context=context)


@login_required(login_url='user-login')
def challengeSubmission(request, id):
    form = QuestionForm()
    instance = get_object_or_404(Challenges, id=id)
    print(instance)
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            challenge_form = form.save(commit=False)
            challenge_form.challenge = instance
            challenge_form.applyer = request.user
            print(challenge_form.applyer)
            challenge_form.save()
            return redirect('challenge-list')

        else:
            print(form.errors)
    context = {
        'form': form,
        'challenge': instance
    }
    return render(request, template_name='challenges/createSubmission.html', context=context)


def challengeDetail(request, id):
    queryset = Challenges.objects.get(id=id)
    submissions = Submission.objects.filter(challenge=queryset)
    submission_count = submissions.count()
    context = {
        'challenges': queryset,
        'submission_count': submission_count,
    }
    return render(request, template_name='challenges/challengeDetail.html', context=context)


@login_required(login_url='user-login')
def CreateChallenge(request):
    form = ChallengeCreationForm()
    if request.method == 'POST':
        form = ChallengeCreationForm(request.POST, request.FILES)
        if form.is_valid():
            challenge = form.save(commit=False)
            challenge.instance.created_by = request.user
            challenge.save()
            return redirect('challenge-list')
        else:
            print(form.errors)

    context = {
        'form': form,
    }
    return render(request, template_name='challenges/challengecreation.html', context=context)


def hosterMyChallenges(request):
    mychallenges = Challenges.objects.filter(created_by=request.user)
    context = {
        'mychallenges': mychallenges
    }
    return render(request, template_name='challenges/myChallenges.html', context=context)


@login_required(login_url='user-login')
def challengeUpdate(request, id):
    instance = get_object_or_404(Challenges, id=id)
    form = ChallengeCreationForm(instance=instance)
    if request.method == 'POST':
        form = ChallengeCreationForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            print('post validated....')
            form.save()
            print('updated...')
            return redirect('challenge-list')
        else:
            print(form.errors)

    context = {
        'form': form
    }
    return render(request, template_name='challenges/challengeUpdation.html', context=context)


@login_required(login_url='user-login')
def viewChallengeSubmission(request, id):
    current_challenge = Challenges.objects.get(id=id)
    submissions_query_set = Submission.objects.filter(challenge=current_challenge, review_status=False).order_by(
        '-submitted_at')
    # review_score = submissions_query_set[1].
    # print(review_score)
    context = {
        'submissions': submissions_query_set,
    }

    return render(request, template_name='challenges/viewSubmissions.html', context=context)


@login_required(login_url='user-login')
def reviewSubmission(request, id):
    current_submission = Submission.objects.get(id=id)
    print(current_submission)
    form = ReviewForm()
    context = {
        'submission': current_submission,
        'form': form,
    }
    if request.method == 'POST':
        try:
            form = ReviewForm(request.POST)
            t_score = int(request.POST.get('criteria1')) + int(request.POST.get('criteria2')) + int(
                request.POST.get('criteria3')) + int(request.POST.get('criteria4')) + int(request.POST.get('criteria5'))
            if form.is_valid():
                review_score = form.save(commit=False)
                review_score.TotalScore = t_score
                review_score.submission = current_submission
                review_score.reviewed_by = request.user
                review_score.submission.review_status = True
                review_score.save()
                return redirect('challenge-list')
            else:
                print(form.errors)

        except IntegrityError:
            messages.error(request, 'Already Reviewed...')

    return render(request, template_name='challenges/challenge_submission_review.html', context=context)


def innovatorMyProposals(request):
    queryset = Submission.objects.filter(applyer=request.user)
    print(queryset)
    context = {
        'submissions': queryset,
    }
    return render(request, template_name='challenges/myProposals.html', context=context)

challenges/templates/challenges/Home.html
{% extends 'challenges/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
   <title>Create Challenge </title>
{% endblock %}


{% block content %}

    <div class="row" style="text-align: center">
        <h3>Engage the brightest minds by running online hackathons & innovation challenges</h3>
        <p class="mt-3 col-12 ">Work better with a cloud-based Virtual Hackathon system</p>
    </div>
    <div class="row">
    <div class="col-5">
        <div class="card">
            <h3 class="card-header"> For Innovators </h3>
            <div class="card-body">
                    <div class="card-text">
                        Where you can submit your Ideas...
                        <br>
                        <a  href="{% url 'innovator-user-registration'  %}" class="btn btn-success mt-3">Signup</a>

                    </div>
            </div>

        </div>
    </div>
    <div class="col-5 ">
         <div class="card">
            <h3 class="card-header"> For Organisation </h3>
            <div class="card-body">
                <div class="card-text p-2">
                        Where you can Host online Hackathons and Competitions....
                    <br>
                    <a  href="{% url 'admin-user-registration' %}" class="btn btn-success mt-3">Signup</a>
                    </div>

            </div>

        </div>
    </div>
    </div>
{% endblock %}

challenges/templates/challenges/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <script src="{% static 'js/jquery-3.3.1.min.js'  %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src=" {% static 'js/bootstrap.min.js' %}"></script>

    {% block head %}
        <title>Base</title>
    {% endblock %}
</head>

<body>
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Hack Hunt</a>
       {% if user.is_authenticated %}
           <h3>{{ request.user }}</h3>
       {% endif %}
  <button class="navbar-toggler"
          type="button" data-toggle="collapse"
          data-target="#navbarNav" aria-controls="navbarNav"
          aria-expanded="false" aria-label="Toggle navigation">

    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-3">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'challenge-list' %}">Challenges</a>
      </li>
        {% if user.is_authenticated %}

             <li class="nav-item">
        <a class="nav-link " href="{% url 'user-profile'%}" >My profile</a>
      </li>

      <li class="nav-item">
        <a class="nav-link " href="{% url 'user-logout' %}" >Logout</a>
      </li>

        {% else %}
            <li class="nav-item">
        <a class="nav-link " href="{% url 'user-login' %}" >Login</a>
      </li>


         <li class="nav-item">
        <a class="nav-link " href="{% url 'home' %}" >Signup</a>
      </li>

        {% endif %}

    </ul>
  </div>
</nav>

{% for m in messages %}
    <h3  class="mt-2" style="text-align: center;color: #6f42c1">{{  m}}</h3>
   {% endfor %}
  <div class="container mt-4">

 {% block content %}
 {% endblock %}

    </div>

</body>
</html>

challenges/templates/challenges/challengeDetail.html
{% extends 'challenges/base.html' %}
{% load static %}
{% block head %}
   <title>Challenge_Detail</title>
{% endblock %}


{% block content %}

    <div class="all-content container mb-5 mt-5" style="background-color: #fafafa" >
        <div class="row" >
            <img  class="img-fluid center ml-auto mr-auto mt-3" src="{{ challenges.challenge_image.url }}" alt="not available"/>
        </div>
        <div class="row mt-5 " style="text-justify: auto">
            <div class="col-md-12 col-xs-2">
            <h2>{{ challenges.challenge_title }}</h2>
            <p class="text-justify">{{ challenges.challenge_description }}</p>
            <h3> No.of Submissions {{ submission_count }}</h3>

                {% if challenges.created_by == request.user %}
                    <a href="{% url 'view-submissions' challenges.id %}"
                        class="btn btn-primary mt-3 mb-5"> View Submissions </a>

                    <a href="{% url 'challenge-update' challenges.id %}"
                        class="btn btn-dark mt-3 mb-5"> Update </a>



                {% else %}
                    <a href="{% url 'challenge-submission' challenges.id %}" class="btn btn-success mt-3 mb-5">Apply </a>
                {% endif %}

            </div>

            </div>
    </div>
{% endblock %}

challenges/templates/challenges/challengeList.html
{% extends 'challenges/base.html' %}
{% load static %}
{% block head %}
   <title>Challenge_List</title>
{% endblock %}


{% block content %}
    <h1> Challenge List </h1>
    {% if request.user.is_staff %}
    <div>
         <a href="{% url 'create-challenge' %}"> Create Challenge </a>
         <a class="ml-3" href="{% url 'my-challenges' %}"> My Challenges </a>
    </div>
        {% else %}
        <div>
          <a class="ml-3" href="{% url 'my-proposals' %}"> My Proposals </a>
        </div>
    {% endif %}
  <div class="row mt-5" style="background-color: #f3f3f3" >
{% for challenge in challenges %}
    <div class="col-sm-6 col-md-4" >
      <div class="card mt-3 " style="border-radius: 7px;">
        <img class="card-img-top img-fluid" src="{{ challenge.challenge_image.url }}" width="400" alt="not available">
        <div class="card-body">
          <h5 class="card-title "><a  class="text-decoration-none" href="{% url 'challenge-detail' challenge.id %}">{{ challenge.challenge_title }}</a></h5>
          <h6>Hosted by {{ challenge.created_by }}</h6>
            <p class="card-text ">{{ challenge.challenge_description | truncatechars:150 }}</p>
        </div>
      </div>
    </div>
{% endfor %}
    </div>



{% endblock %}

challenges/templates/challenges/challengeUpdation.html
{% extends 'challenges/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
   <title>Update Challenge</title>
{% endblock %}


{% block content %}
    <div class="jumbotron mt-4">
    <h2>Update Challenge Details</h2>
    <div class="mt-4">
            <form action="" method="POST" enctype="multipart/form-data">
                 {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-primary" type="submit"> Update </button>
            </form>
    </div>
</div>

{% endblock %}

challenges/templates/challenges/challenge_submission_review.html
{% extends 'challenges/base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% block head %}
   <title>Submission List </title>
{% endblock %}


{% block content %}

    <div class="all-content container mb-5 mt-5" style="background-color: #fafafa" >
         <h2>Review Submission</h2>
        <div class="row" style="display: inline">
            <h4>Submitted by </h4><p>{{ submission.applyer }}</p>
        </div>
        <div class="row p-2">

            <div class="container qa1">
                <h3> 1.Can you describe the problem in your own words exactly how you experience it ? </h3>
                <div class="row p-3" style="background-color: white">
                    {{ submission.qa1 }}
                 </div>
             </div>

            <div class="container qa2">
                <h3> 2.How have you tried to solve this problem before? Can you explain the solution ? </h3>
                <div class="row p-3" style="background-color: white">
                    {{ submission.qa2 }}
                 </div>
             </div>

        <div class="container qa3">
                <h3>3.Why did you not make tht solution permanent?What were the gaps in the solution ?</h3>
                <div class="row p-3" style="background-color: white">
                    {{ submission.qa3 }}
                 </div>
             </div>

            <div class="container qa4">
                <h3>4.What are the other constraints?challenges that have to be overcome or accommodated while '
                         'solving the problem?</h3>
                <div class="row p-3" style="background-color: white">
                    {{ submission.qa4 }}
                 </div>
             </div>

            <div class="container qa5">
                <h3>5.How will you benefit from solving the problem?How much is solving this problem worth to you ?</h3>
                <div class="row p-3" style="background-color: white">
                    {{ submission.qa5 }}
                 </div>
             </div>

             <div class="container qa6">
                <h3>6.How important to you is solving this problem among other priorities ?</h3>
                <div class="row p-3" style="background-color: white">
                    {{ submission.qa6 }}
                 </div>
             </div>

        </div>

        <div class="row pl-2 mt-5 ">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <button class=" btn btn-success" type="submit"> Submit Scores </button>
            </form>
        </div>


    </div>
{% endblock %}

challenges/templates/challenges/challengecreation.html
{% extends 'challenges/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
   <title>Create Challenge </title>
{% endblock %}


{% block content %}
    <div class="jumbotron mt-4">
    <h2>Create a Challenge</h2>
    <div class="mt-4">
            <form action="" method="POST" enctype="multipart/form-data">
                 {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-primary" type="submit"> Create </button>
            </form>
    </div>
</div>

{% endblock %}

challenges/templates/challenges/createSubmission.html
{% extends 'challenges/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
   <title>Create Submission</title>
{% endblock %}


{% block content %}
<div class="jumbotron">
    <h2>Application for : {{ challenge.challenge_title }}</h2>
    <div class="mt-4">
            <form action="" method="POST">
                 {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-primary" type="submit"> Submit </button>
            </form>
    </div>
</div>

{% endblock %}

challenges/templates/challenges/enable_review_status.html
{% extends 'challenges/base.html' %}
{% load static %}
{% block head %}
   <title>Review_Status_Enable</title>
{% endblock %}


{% block content %}
    <h2>Enable_Review</h2>



{% endblock %}

challenges/templates/challenges/myChallenges.html
{% extends 'challenges/base.html' %}
{% load static %}
{% block head %}

 <title>MyChallenges</title>
{% endblock %}


{% block content %}

     <h1>  My Challenges  </h1>

  <div class="row mt-5" style="background-color: #f3f3f3" >
{% for challenge in mychallenges %}
    <div class="col-sm-6 col-md-4" >
      <div class="card mt-3 " style="border-radius: 7px;">
        <img class="card-img-top img-fluid" src="{{ challenge.challenge_image.url }}" width="400"  alt="not available">
        <div class="card-body">
          <h5 class="card-title "><a  class="text-decoration-none" href="{% url 'challenge-detail' challenge.id %}">{{ challenge.challenge_title }}</a></h5>
          <p class="card-text "> No.of Submissions  : <b> {{ challenge.submission_set.count}}</b></p>
        </div>
      </div>
    </div>
{% endfor %}
    </div>


{% endblock %}

challenges/templates/challenges/myProposals.html
{% extends 'challenges/base.html' %}
{% load static %}
{% block head %}
   <title>My Proposals </title>
{% endblock %}


{% block content %}

    <div class="all-content container mb-5 mt-5" style="background-color: #fafafa" >
      <h1>My Proposals</h1>
     <div class="submissions pb-4  container"  >
        {% for submission in submissions %}
                <div class="container mt-4  " style="border: 1px grey solid" >
                <div class="row mt-4">
                    <div class="col mt-1 pb-1 ">
                        <h2> {{ submission.challenge }}</h2>
                        <small> Reviewed by : {{ submission.reviewsubmissionscore.reviewed_by }}</small>
                        <br>
                        {% if submission.reviewsubmissionscore.tip == '' %}
                         <small> No remarks and suggestions from reviewers</small>
                        {% else %}
                        <h4> Tip : {{ submission.reviewsubmissionscore.tip }}</h4>
                        {% endif %}

                    </div>
                   <div class="col mt-1 pb-1">
                        <p>Score : {{submission.reviewsubmissionscore.TotalScore}}</p>
                        {% if submission.reviewsubmissionscore.TotalScore == '' %}
                        <p>Review_Status : "Not Reviewed"</p>
                        {% else%}
                            <p>Review_Status : "Reviewed"</p>
                        {% endif %}
                   </div>
                </div>
                 </div>
        {% endfor %}
    </div>
      </div>
{% endblock %}

challenges/templates/challenges/viewSubmissions.html
{% extends 'challenges/base.html' %}
{% load static %}
{% block head %}
   <title>Submission List </title>
{% endblock %}


{% block content %}

    <div class="all-content container mb-5 mt-5" style="background-color: #fafafa" >
      <h1>List of Submissions </h1>
    <div class=" submissions container" >
        {% for submission in submissions %}
                <div class="container" style="border: 1px grey solid" >
                <div class="row mt-4">
                    <div class="col mt-3 pb-3 ">
                        <h3>{{ submission.applyer}}</h3>
                    </div>
                   <div class="col mt-3 pb-3">


                        <a href="{% url 'review-submissions' submission.id %}" class=" btn btn-success">Review</a>
                        <a href="#" class="btn btn-info ml-2">Assign to Reviewers </a>
                   
                   </div>

                </div>

                 </div>
        {% endfor %}
    </div>
    </div>
{% endblock %}